name: Build Nebys OS ISO

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm archiso git grub syslinux

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        run: |
          mkdir -p out work
          mkarchiso -v -w ./work -o ./out .

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nebysos-iso
          path: out/*.iso
          if-no-files-found: error
